### ISSUE TITLE
How to get space children names?

### ISSUE THREAD

**Issue by JohnGebbie** [mautrix/go#91] opened 2022-09-18 22:49 UTC
Funny title but I can't figure out how to get the names of the rooms in a space.
I'm stuck with only the roomIDs from room.State[event.StateSpaceChild].
I tried getting the state events with client.State(roomID) but it gets denied due to permissions.

I see there is a GET /hierarchy api which I don't think is in mautrix yet. Would that be the only way? Thank you.

**Comment by mgcm** [comment] 2022-11-06 09:27
the /hierarchy endpoint got merged so you now have that but yeah, by design, you're only supposed to get room metadata if you have permissions.

**Closed** 2022-11-06 10:27 UTC
